### ISSUE TITLE
variable @gutter-cursor-emph is undefined

### ISSUE THREAD

**Issue by averrin** [dktn/resonance-ui#2]
Just run atom.
version: 1.10-beta5

variable @gutter-cursor-emph is undefined in /home/user/.atom/packages/resonance-ui/styles/editor.less:97:43

LessError: variable @gutter-cursor-emph is undefined
  at /home/user/.atom/packages/resonance-ui/styles/editor.less:97:43

**Comment by dktn** [comment]
Try to download the newest version. If it doesn't work - uninstall and install again. It should work. In case it still doesn't, please let me know.
