### ISSUE TITLE
Tree view scroller

### ISSUE THREAD

**Issue by Robust1308** [dktn/resonance-ui#4]
Thank for your work. I really like your UI and syntax theme
Yet I have noticed the tree view scroll bar issue, there is a black area next to the scroll bar and some weird stuff display on that black area.

![screenshot from 2016-08-27 10-51-19](https://cloud.githubusercontent.com/assets/19568007/18024983/74dbe09a-6c44-11e6-9171-7d95f26708c3.png)

![image](https://cloud.githubusercontent.com/assets/19568007/18025000/e88b52dc-6c44-11e6-8d8d-44b6a88507aa.png)

Cheer!

**Comment by dktn** [comment]
I don't have this issue (on Mac OS X and Linux). What operating system are you running?
Unfortunatelly I am not CSS/LESS expert, the theme is just a result of random playing with it ;)

Can you go to the code `.atom/packages/resonance-ui` and remove `.scrollbars-visible-always` section from `styles/atom.css` file and see what happens (Atom restart may be necessary). The same experiment with re-enabling commented `::-webkit-scrollbar` section from the same file. Let me know what happens, please.

**Comment by Robust1308** [comment]
Hi. I'm using Ubuntu 16.0
I have tried what you said but it still appears :(
It's fine, maybe my OS issue.
Thank for your help.

P/S: Love your work.

**Comment by Robust1308** [comment]
Hurray! I've just updated to version 0.11.0 and the issue gone :+1: 
Thank you.

**Comment by dktn** [comment]
I'm happy to hear that! :)
